import ApiDocsConfig from "../ApiDocsConfig";

export default class ApiDocsMdPart {
  constructor(private readonly config: ApiDocsConfig) {}

  get title(): string {
    let result = "";
    result += `---\ntitle: ${this.config.title || ""}\n---\n\n`;
    result += "<!-- Automatically generated by sfa-router -->\n\n";
    const config = this.config;
    if (config.title) {
      result += `# ${config.title}\n\n`;
    }
    if (config.subtitle) {
      result += `${config.subtitle}\n\n`;
    }
    return result;
  }

  get separation(): string {
    return `\n\n---\n\n`;
  }

  get tail(): string {
    return "\n";
  }
}
