name: "Publish NPM"

on:
  push:
    tags:
      - "v\\d+\\.\\d+\\.\\d+" # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [18, 20]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
      - run: sh scripts/ci-install.sh
      - name: Run test
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
        run: npm run test
      - run: npx codecov

  publish-npm:
    if: github.repository == 'halsp/core'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: sh scripts/ci-install.sh
      - run: npm run build
      - run: npx lerna publish from-package -y -m "chore(release):\ publish %s"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  sync-cnpm:
    if: github.repository == 'halsp/core'
    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: sh scripts/ci-install.sh
      - run: npx ts-node scripts/sync-cnpm.ts
