name: "Publish NPM"

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [14, 16, 18]
        include:
          # Active LTS + other OS
          - os: macos-latest
            node_version: 16
          - os: windows-latest
            node_version: 16
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: sh scripts/install-yarn.sh
      - run: npm run bootstrap
      - name: Run test
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
        run: npm run test
      - run: npx codecov

  publish-npm:
    if: github.repository == 'ipare/ipare'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: https://registry.npmjs.org/
      - run: sh scripts/install-yarn.sh
      - run: npm run bootstrap
      - run: npm run build
      - run: npx lerna publish from-package -y -m "chore(release):\ publish %s"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
